version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
init:
- ps: "if (-not (Test-Path env:DXSDK_DIR2)) \n{\nStart-FileDownload 'https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe' -FileName 'C:\\DXSDK_Jun10.exe'\nStart-FileDownload 'https://github.com/chocolatey/chocolatey/raw/master/src/redirects/RefreshEnv.cmd' -FileName 'C:\\RefreshEnv.cmd'\nStart-Process \"C:\\DXSDK_Jun10.exe\" \"/F /S /O /U\" -NoNewWindow -Wait\nC:\\RefreshEnv.cmd\n}\n\n\n$releases = \"https://github.com/ThirteenAG/modupdater/releases\"\n$name = \"modupdater.zip\"\n$latestRelease = Invoke-WebRequest $releases/latest -Headers @{\"Accept\"=\"application/json\"}\n$json = $latestRelease.Content | ConvertFrom-Json\n$latestVersion = $json.tag_name\n$url = \"$releases/download/$latestVersion/$name\"\n\nStart-FileDownload $url -FileName 'C:\\modupdater.zip'\n7z e c:\\modupdater.zip -oc:\\Projects\\modupdater\\bin\\Release"
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
before_build:
- cmd: 
build:
  project: build/WidescreenFixesPack.sln
  verbosity: minimal
before_package:
- cmd: >-
    cd ..


    git clone https://github.com/ThirteenAG/Ultimate-ASI-Loader --recursive

    cd Ultimate-ASI-Loader

    premake5.bat

    msbuild.exe build/Ultimate-ASI-Loader-x86.sln /t:Build /p:Configuration=Release;Platform=Win32

    cd ..


    git clone https://github.com/ThirteenAG/d3d8-wrapper --recursive

    cd d3d8-wrapper

    premake5.bat

    msbuild.exe build/d3d8-wrapper.sln /t:Build /p:Configuration=Release;Platform=Win32

    cd ..


    git clone https://github.com/ThirteenAG/d3d9-wrapper --recursive

    cd d3d9-wrapper

    premake5.bat

    msbuild.exe build/d3d9-wrapper.sln /t:Build /p:Configuration=Release;Platform=Win32

    cd ..


    cd widescreenfixespack/data

    release.bat
after_build:
- ps: Get-ChildItem .\Archives\*.zip  | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }