version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
init:
- ps: >-
    Start-FileDownload 'https://download.microsoft.com/download/A/E/7/AE743F1F-632B-4809-87A9-AA1BB3458E31/DXSDK_Jun10.exe' -FileName 'C:\DXSDK_Jun10.exe'

    $exitCode = [Diagnostics.Process]::Start("C:\DXSDK_Jun10.exe","/F /S /O /U").WaitForExit(100000)


    Start-FileDownload 'https://github.com/chocolatey/chocolatey/raw/master/src/redirects/RefreshEnv.cmd' -FileName 'C:\RefreshEnv.cmd'
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
before_build:
- cmd: C:\RefreshEnv.cmd
build:
  project: build/WidescreenFixesPack.sln
  verbosity: minimal
before_package:
- cmd: >-
    cd ..


    git clone https://github.com/ThirteenAG/Ultimate-ASI-Loader --recursive

    Ultimate-ASI-Loader/premake5.bat

    msbuild.exe Ultimate-ASI-Loader/build/Ultimate-ASI-Loader-x86.sln /t:Build /p:Configuration=Release;Platform=Win32


    git clone https://github.com/ThirteenAG/d3d8-wrapper --recursive

    d3d8-wrapper/premake5.bat

    msbuild.exe d3d8-wrapper/build/d3d8-wrapper.sln /t:Build /p:Configuration=Release;Platform=Win32


    git clone https://github.com/ThirteenAG/d3d9-wrapper --recursive

    d3d9-wrapper/premake5.bat

    msbuild.exe d3d9-wrapper/build/d3d9-wrapper.sln /t:Build /p:Configuration=Release;Platform=Win32


    cd widescreenfixespack/data

    release.bat
after_build:
- ps: Get-ChildItem .\Archives\*.zip  | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }