version: '{build}'
skip_tags: true
configuration: Release
install:
- cmd: >-
    git submodule update --init --recursive

    premake5.bat
build:
  project: build/WidescreenFixesPack.sln
  verbosity: minimal
before_package:
- cmd: >-
    cd ..

    git clone https://github.com/ThirteenAG/Ultimate-ASI-Loader --recursive

    cd Ultimate-ASI-Loader

    premake5.bat

    msbuild.exe build/Ultimate-ASI-Loader-x86.sln /t:Build /p:Configuration=Release;Platform=Win32

    cd ..

    cd widescreenfixespack


    cd data

    release.bat
after_build:
- ps: Get-ChildItem .\Archives\*.zip  | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }