name: "Build All"

inputs:
  project:
    description: "Project name"
    required: false

runs:
  using: "composite"
  steps:
  - name: Add msbuild to PATH
    uses: microsoft/setup-msbuild@v1.1
  - uses: actions/checkout@v3
    with:
      submodules: 'true'
#  - name: DX SDK
#    shell: bash
#    run:  |
#      curl -L https://download.microsoft.com/download/a/e/7/ae743f1f-632b-4809-87a9-aa1bb3458e31/DXSDK_Jun10.exe -o DX.exe
#      7z x DX.exe DXSDK/Include -oDX
#      7z x DX.exe DXSDK/Lib/x86 -oDX
#      mv DX/DXSDK "C:/Program Files (x86)/Microsoft DirectX SDK (June 2010)"
  - name: Configure build
    shell: cmd
    run: |
      ./premake5.bat
  - name: Before Build
    shell: cmd
    run: |
      ./before_build.bat
  - name: Build
    shell: cmd
    run: |
      msbuild -m build/WidescreenFixesPack.sln ${{inputs.project}} /property:Configuration=${{matrix.buildtype}} /property:Platform=${{matrix.platform}}
  - name: Before Package
    shell: cmd
    run: |
      ./before_packaging.bat
  - name: Pack binaries
    shell: cmd
    run: |
      cd ./data
      release.bat
  - name: Upload artifacts to actions
    uses: actions/upload-artifact@v3.1.2
    with:
      path: ./data/Archives/*.zip
