version: 2.1

orbs:
  win: circleci/windows@2.4.1

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Before build
          command: |
            git submodule update --init --recursive
            ./premake5.exe vs2019
            choco install directx-sdk
            ./before_build.bat
      - run:
          name: MSBuild
          command: |
            cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\msbuild\current\bin\"
            .\msbuild.exe "C:\Users\circleci\project\build\WidescreenFixesPack.sln"
 