version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
      name: win/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: Before build
          command: |
            git submodule update --init --recursive
            ./premake5.exe vs2022
            choco feature enable -n allowGlobalConfirmation
            choco install directx-sdk
            ./before_build.bat
      - run:
          name: MSBuild
          command: |
            "C:\Program Files\Microsoft Visual Studio\2022\Community\msbuild\current\bin\msbuild.exe build\WidescreenFixesPack.sln"
 
