name: Release All

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [Win32]
        buildtype: [Release]

    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/build_all
    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: gtasade
        artifacts: data/Archives/GTASADE.FusionMod.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: gta3de
        artifacts: data/Archives/GTA3DE.FusionMod.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: gtavcde
        artifacts: data/Archives/GTAVCDE.FusionMod.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: gtasa
        artifacts: data/Archives/GTASA.WidescreenFix.zip, data/Archives/GTASA.WidescreenFrontend.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: scdaps2
        artifacts: data/Archives/SplinterCellDoubleAgent.PCSX2.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: burnout3
        artifacts: data/Archives/Burnout3.PCSX2.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: condemned
        artifacts: data/Archives/Condemned.MissingSteamFilesFix.Lite.zip, data/Archives/Condemned.MissingSteamFilesFix.zip, data/Archives/Condemned.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: kr2
        artifacts: data/Archives/KnightRider2.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: kr
        artifacts: data/Archives/KnightRider.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: farcry
        artifacts: data/Archives/FarCry.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: nfsuc
        artifacts: data/Archives/NFSUndercover.GenericFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: nfsps
        artifacts: data/Archives/NFSProStreet.GenericFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: masseffect
        artifacts: data/Archives/MassEffectTrilogy.FOVFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: bully
        artifacts: data/Archives/Bully.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: larush
        artifacts: data/Archives/LARush.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: thegodfather
        artifacts: data/Archives/TheGodfather.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: psychonauts
        artifacts: data/Archives/Psychonauts.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: justcause
        artifacts: data/Archives/JustCause.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: thematrixpathofneo
        artifacts: data/Archives/TheMatrixPathOfNeo.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: enterthematrix
        artifacts: data/Archives/EnterTheMatrix.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: hd2
        artifacts: data/Archives/HiddenandDangerous2.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: usm
        artifacts: data/Archives/UltimateSpiderMan.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: driv3r
        artifacts: data/Archives/Driv3r.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: thesuffering
        artifacts: data/Archives/TheSuffering.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: sh4
        artifacts: data/Archives/SilentHill4.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: driverpl
        artifacts: data/Archives/DriverParallelLines.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: callofcthulhu
        artifacts: data/Archives/CallOfCthulhu.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: kingkong
        artifacts: data/Archives/KingKong.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: onimusha3
        artifacts: data/Archives/Onimusha3.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: sh3
        artifacts: data/Archives/SilentHill3.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: sh2
        artifacts: data/Archives/SilentHill2.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: coldfear
        artifacts: data/Archives/ColdFear.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: paradisecracked
        artifacts: data/Archives/ParadiseCracked.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: nfsu
        artifacts: data/Archives/NFSUnderground.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: nfsu2
        artifacts: data/Archives/NFSUnderground2.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: nfsmw
        artifacts: data/Archives/NFSMostWanted.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: nfsc
        artifacts: data/Archives/NFSCarbon.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: manhunt
        artifacts: data/Archives/Manhunt.WidescreenFix.zip, data/Archives/Manhunt.WidescreenFrontend.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: gun
        artifacts: data/Archives/Gun.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: flatoutuc
        artifacts: data/Archives/FlatoutUltimateCarnage.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: flatout2
        artifacts: data/Archives/Flatout2.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: flatout
        artifacts: data/Archives/Flatout.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: fahrenheit
        artifacts: data/Archives/Fahrenheit.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: dmc3se
        artifacts: data/Archives/DevilMayCry3.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: da4
        artifacts: data/Archives/DeerAvenger4.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: mafia
        artifacts: data/Archives/Mafia.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: tod
        artifacts: data/Archives/TotalOverdose.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: thug2
        artifacts: data/Archives/TonyHawksUnderground2.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: thug
        artifacts: data/Archives/TonyHawksUnderground.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: thps4
        artifacts: data/Archives/TonyHawksProSkater4.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: thps3
        artifacts: data/Archives/TonyHawksProSkater3.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: thps2
        artifacts: data/Archives/TonyHawksProSkater2.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: thaw
        artifacts: data/Archives/TonyHawksAmericanWasteland.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: punisher
        artifacts: data/Archives/ThePunisher.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: secondsight
        artifacts: data/Archives/SecondSight.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: psiops
        artifacts: data/Archives/PsiOpsTheMindgateConspiracy.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: mp2
        artifacts: data/Archives/MaxPayne2.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: mp1
        artifacts: data/Archives/MaxPayne.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: gtasa-wshps
        artifacts: data/Archives/GTASA.WidescreenFix.Archived.zip, data/Archives/wshps.asi

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: gtavc
        artifacts: data/Archives/GTAVC.WidescreenFix.zip, data/Archives/GTAVC.WidescreenFrontend.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: gta3
        artifacts: data/Archives/GTA3.WidescreenFix.zip, data/Archives/GTA3.WidescreenFrontend.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: gta2
        artifacts: data/Archives/GTA2.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: gta1
        artifacts: data/Archives/GTA1.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: truecrimesola
        artifacts: data/Archives/TrueCrimeStreetsofLA.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: truecrimenyc
        artifacts: data/Archives/TrueCrimeNewYorkCity.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: stubbsthezombie
        artifacts: data/Archives/StubbstheZombie.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: srs
        artifacts: data/Archives/StreetRacingSyndicate.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: scda
        artifacts: data/Archives/SplinterCellDoubleAgent.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: scct
        artifacts: data/Archives/SplinterCellChaosTheory.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: scpt
        artifacts: data/Archives/SplinterCellPandoraTomorrow.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: sc
        artifacts: data/Archives/SplinterCell.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: sniperelite
        artifacts: data/Archives/SniperElite.WidescreenFix.zip

    - uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        tag: sonicheroes
        artifacts: data/Archives/SonicHeroes.WidescreenFix.zip

