name: enterthematrix

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ThirteenAG/WidescreenFixesPack/.github/workflows/all.yml@master
    with:
      tag_list: enterthematrix
      project: /t:EnterTheMatrix_WidescreenFix
