name: GitHub Actions Build

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [Win32]
        buildtype: [Release]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Build Solution
      uses: ./.github/workflows/build_all
    - name: Check PR
      uses: 8BitJonny/gh-get-current-pr@2.2.0
      id: pr
    - name: Update Tags
      if: ${{ github.ref == 'refs/heads/master' }} && steps.pr.outputs.number != 'null'
      uses: ThirteenAG/update-tags@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
