name: nfsmw

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ThirteenAG/WidescreenFixesPack/.github/workflows/all.yml@master
    with:
      tag_list: nfsmw
      project: /t:NFSMostWanted_WidescreenFix
