name: scct

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ThirteenAG/WidescreenFixesPack/.github/workflows/all.yml@master
    with:
      tag_list: scct
      project: /t:SplinterCellChaosTheory_WidescreenFix
