name: scdaxbox

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ThirteenAG/WidescreenFixesPack/.github/workflows/all.yml@master
    with:
      tag_list: scdaxbox
      project: /t:SplinterCellDoubleAgent_CXBXR_WidescreenFix
