name: thesuffering

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ThirteenAG/WidescreenFixesPack/.github/workflows/all.yml@master
    with:
      tag_list: thesuffering
      project: /t:TheSuffering_WidescreenFix
