name: thps4

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ThirteenAG/WidescreenFixesPack/.github/workflows/all.yml@master
    with:
      tag_list: thps4
      project: /t:TonyHawksProSkater4_WidescreenFix
