name: thps3

on:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: ThirteenAG/WidescreenFixesPack/.github/workflows/all.yml@master
    with:
      tag_list: thps3
      project: /t:TonyHawksProSkater3_WidescreenFix
